var JOURNAL = [
  {"events":["marchewka","ćwiczenia","weekend"],"squirrel":false},
  {"events":["chleb","budyń","mycie zębów","weekend","dotknięcie drzewa"],"squirrel":false},
  {"events":["marchewka","nachos","mycie zębów","rower","weekend"],"squirrel":false},
  {"events":["brussel sprouts","lody","mycie zębów","komputer","weekend"],"squirrel":false},
  {"events":["ziemniaki","cukierek","mycie zębów","ćwiczenia","weekend","dentist"],"squirrel":false},
  {"events":["brussel sprouts","budyń","mycie zębów","bieganie","weekend"],"squirrel":false},
  {"events":["pizza","mycie zębów","komputer","praca","dotknięcie drzewa"],"squirrel":false},
  {"events":["chleb","beer","mycie zębów","rower","praca"],"squirrel":false},
  {"events":["kalafior","mycie zębów","praca"],"squirrel":false},
  {"events":["pizza","mycie zębów","rower","praca"],"squirrel":false},
  {"events":["lasagna","nachos","mycie zębów","praca"],"squirrel":false},
  {"events":["mycie zębów","weekend","dotknięcie drzewa"],"squirrel":false},
  {"events":["sałata","mycie zębów","telewizja","weekend"],"squirrel":false},
  {"events":["spaghetti","mycie zębów","praca"],"squirrel":false},
  {"events":["mycie zębów","komputer","praca"],"squirrel":false},
  {"events":["sałata","nachos","mycie zębów","praca"],"squirrel":false},
  {"events":["marchewka","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["mycie zębów","praca"],"squirrel":false},
  {"events":["kalafior","czytanie","weekend"],"squirrel":false},
  {"events":["chleb","mycie zębów","weekend"],"squirrel":false},
  {"events":["lasagna","mycie zębów","ćwiczenia","praca"],"squirrel":false},
  {"events":["spaghetti","mycie zębów","czytanie","praca"],"squirrel":false},
  {"events":["marchewka","lody","mycie zębów","telewizja","praca"],"squirrel":false},
  {"events":["spaghetti","nachos","praca"],"squirrel":false},
  {"events":["kalafior","lody","mycie zębów","rower","praca"],"squirrel":false},
  {"events":["spaghetti","orzeszki","komputer","weekend"],"squirrel":true},
  {"events":["ziemniaki","lody","mycie zębów","komputer","weekend"],"squirrel":false},
  {"events":["ziemniaki","lody","mycie zębów","praca"],"squirrel":false},
  {"events":["orzeszki","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["ziemniaki","ćwiczenia","praca"],"squirrel":false},
  {"events":["pizza","lody","komputer","praca"],"squirrel":false},
  {"events":["lasagna","lody","praca"],"squirrel":false},
  {"events":["kalafior","cukierek","czytanie","weekend"],"squirrel":false},
  {"events":["lasagna","nachos","mycie zębów","bieganie","weekend"],"squirrel":false},
  {"events":["ziemniaki","mycie zębów","praca"],"squirrel":false},
  {"events":["marchewka","praca"],"squirrel":false},
  {"events":["pizza","beer","praca","dentist"],"squirrel":false},
  {"events":["lasagna","budyń","rower","praca"],"squirrel":false},
  {"events":["spaghetti","mycie zębów","czytanie","praca"],"squirrel":false},
  {"events":["spaghetti","budyń","telewizja","weekend"],"squirrel":false},
  {"events":["chleb","mycie zębów","ćwiczenia","weekend"],"squirrel":false},
  {"events":["lasagna","orzeszki","praca"],"squirrel":true},
  {"events":["pizza","praca"],"squirrel":false},
  {"events":["ziemniaki","ćwiczenia","praca"],"squirrel":false},
  {"events":["mycie zębów","ćwiczenia","praca"],"squirrel":false},
  {"events":["spaghetti","mycie zębów","telewizja","praca"],"squirrel":false},
  {"events":["pizza","rower","weekend"],"squirrel":false},
  {"events":["marchewka","mycie zębów","weekend"],"squirrel":false},
  {"events":["marchewka","beer","mycie zębów","praca"],"squirrel":false},
  {"events":["pizza","orzeszki","cukierek","praca"],"squirrel":true},
  {"events":["marchewka","orzeszki","mycie zębów","czytanie","praca"],"squirrel":false},
  {"events":["ziemniaki","orzeszki","mycie zębów","praca"],"squirrel":false},
  {"events":["marchewka","nachos","mycie zębów","ćwiczenia","praca"],"squirrel":false},
  {"events":["pizza","orzeszki","mycie zębów","telewizja","weekend"],"squirrel":false},
  {"events":["lasagna","mycie zębów","rower","weekend"],"squirrel":false},
  {"events":["kalafior","orzeszki","mycie zębów","komputer","praca","dotknięcie drzewa"],"squirrel":false},
  {"events":["sałata","mycie zębów","telewizja","praca"],"squirrel":false},
  {"events":["ziemniaki","mycie zębów","komputer","praca"],"squirrel":false},
  {"events":["chleb","cukierek","praca"],"squirrel":false},
  {"events":["ziemniaki","nachos","praca"],"squirrel":false},
  {"events":["marchewka","budyń","mycie zębów","weekend"],"squirrel":false},
  {"events":["marchewka","mycie zębów","ćwiczenia","weekend","dotknięcie drzewa"],"squirrel":false},
  {"events":["brussel sprouts","bieganie","praca"],"squirrel":false},
  {"events":["mycie zębów","praca"],"squirrel":false},
  {"events":["sałata","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["cukierek","mycie zębów","praca"],"squirrel":false},
  {"events":["brussel sprouts","mycie zębów","komputer","praca"],"squirrel":false},
  {"events":["chleb","mycie zębów","weekend"],"squirrel":false},
  {"events":["kalafior","mycie zębów","weekend"],"squirrel":false},
  {"events":["spaghetti","cukierek","telewizja","praca","dotknięcie drzewa"],"squirrel":false},
  {"events":["marchewka","budyń","mycie zębów","praca"],"squirrel":false},
  {"events":["sałata","mycie zębów","praca"],"squirrel":false},
  {"events":["marchewka","lody","mycie zębów","rower","praca"],"squirrel":false},
  {"events":["pizza","mycie zębów","praca"],"squirrel":false},
  {"events":["spaghetti","orzeszki","ćwiczenia","weekend"],"squirrel":true},
  {"events":["chleb","beer","komputer","weekend","dotknięcie drzewa"],"squirrel":false},
  {"events":["mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["sałata","orzeszki","mycie zębów","praca","dotknięcie drzewa"],"squirrel":false},
  {"events":["lasagna","mycie zębów","telewizja","praca"],"squirrel":false},
  {"events":["kalafior","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["marchewka","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["marchewka","czytanie","weekend"],"squirrel":false},
  {"events":["marchewka","orzeszki","czytanie","weekend"],"squirrel":true},
  {"events":["ziemniaki","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["lasagna","lody","praca","dotknięcie drzewa"],"squirrel":false},
  {"events":["kalafior","orzeszki","mycie zębów","rower","praca"],"squirrel":false},
  {"events":["pizza","mycie zębów","bieganie","praca"],"squirrel":false},
  {"events":["sałata","mycie zębów","praca"],"squirrel":false},
  {"events":["chleb","mycie zębów","telewizja","weekend"],"squirrel":false},
  {"events":["kalafior","orzeszki","mycie zębów","weekend"],"squirrel":false}
];

// Eksport danych do node.js —
// `require('./path/to/journal.js')` zapewnia tablicę.
if (typeof module != "undefined" && module.exports && (typeof window == "undefined" || window.exports != exports))
  module.exports = JOURNAL;
if (typeof global != "undefined" && !global.JOURNAL)
  global.JOURNAL = JOURNAL;
